### ISSUE TITLE
Lack of llm_funcs.py?

### ISSUE THREAD

**Issue by yychenca** [phunterlau/papercast#1]
I got the following error when running the examples (python run.py examples/run_attention.yaml)

```
Traceback (most recent call last):
  File "run.py", line 1, in <module>
    from summarizer import generate_summary_arxiv
  File "C:\Users\yyche\Documents\sources\repos\papercast\summarizer.py", line 3, in <module>
    from llm_funcs import gen_gpt_chat_completion
ModuleNotFoundError: No module named 'llm_funcs'
```

Is llm_funcs a custom .py file or a library to be installed?

**Comment by phunterlau** [comment]
oops, you are right. Thanks for finding it. Sorry I refactorized the code and move them out. Please check the commit for the quick fix.

**Comment by yychenca** [comment]
Confirming issue solved. Thanks!
